version = 1

[[analyzers]]
name = "scala"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "php"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/rohank-deepsource/Gigarepo"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"